"""add password_hash

Revision ID: 8e0cd56aecc4
Revises: 3591abc4e0ea
Create Date: 2023-06-04 19:33:48.139741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e0cd56aecc4'
down_revision = '3591abc4e0ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('password_hash')
        batch_op.drop_column('login')

    # ### end Alembic commands ###
